name: smooth_star_rating
description: A smooth rating bar
version: 1.0.3
authors:
- Thangmam <infimatet@gmail.com>
- Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/thangmam/smoothratingbar.git

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
